baseURL: http://queuepal.onrender.com/
languageCode: en-us
title: QueuePal
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Zero-contact, text-based check-ins to replace lines and waiting rooms.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/WaitPal-Logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Zero-Contact Waiting
    # Hero subtitle (optional)
    subtitle: Zero-contact, text-based check-ins to replace lines and waiting rooms.
    # Button text
    buttontext: Contact Us
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from static/images/___)
    image: illustrations/undraw_personal_text_vkd8.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: "#features"
  - title: Contact
    url: "#contact"
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # section1:
  #   title: Keep Your Patients Safe
  #   subtitle: Without Being Glued to Your Phone
  #   tiles:
  #   - title: Automatic Check-In Prompts
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: HIPAA Compliant
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Engaged Patients
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  section2:
    title: Features
    subtitle: Keep Patients Safe While Streamlining Your Check-In Process
    features:
    - title: Automatic Check-In Prompts
      text: 15 minutes prior to scheduled appointment time patients will receive a text that they can reply to to easily check-in
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Engaged Patients
      text: After checking-in, patients receive a link to engaging health and wellness content to view while waiting.
      icon: doc-sync
    - title: Mobile and Web
      text: View your schedule, add appointments, and see patients check-in live on either mobile or web.
      icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  section4:
    title: What Our Clients Say
    subtitle: Over 20 patients checked-in and counting
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    # - name: John Bradley
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Financial Analyst
    #   img: 2
    # - name: Gary Blackman
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: HR Manager
    #   img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: WaitPal-Logo.svg
    # Social Media Title
    # socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    # - link: https://github.com/lucperkins/github-fresh
    #   # Icons are from Font Awesome
    #   icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: true
    # quicklinks:
    #   column1:
    #     title: "Product"
    #     links:
    #     - text: Discover features
    #       link: /
    #     - text: Why choose our product?
    #       link: /
    #     - text: Compare features
    #       link: /
    #     - text: Our roadmap
    #       link: /
    #     - text: AGB
    #       link: /agb
    #   column2:
    #     title: "Docs"
    #     links:
    #     - text: Get started
    #       link: /
    #     - text: User guides
    #       link: /
    #     - text: Admin guide
    #       link: /
    #     - text: Developers
    #       link: /
    #   column3:
    #     title: "Blog"
    #     links:
    #     - text: Latest news
    #       link: /blog/first
    #     - text: Tech articles
    #       link: /blog/second
